title: Gastro-intestinal cancer research
author: wwadddingham
email: w.waddingham@ucl.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Studying cancer precursor lesions in the stomach and oesophagus, to inform endoscopic surveillance strategies for early diagnosis.
  
theme: minima 
# social links
github_username:  wwaddingham

show_excerpts: true # set to false to remove excerpts on the homepage
